-- Generated by protoc-gen-elmgen. DO NOT EDIT!


module Example exposing (..)

-- This module is broken down into: records (messages), unions (enums), oneofs, empty constructors (zero values), decoders, and encoders
-- Records: AllTogether AllTogether_NestedAbc Scalar
-- Unions: AllTogether_Answer
-- Oneofs: AllTogether_Favourite

import Bytes exposing (Bytes)
import Bytes.Encode as BE
import Dict exposing (Dict)
import Protobuf.Decode as PD
import Protobuf.Encode as PE


type alias AllTogether =
    { myList : List String
    , myMap : Dict String Bool
    , favourite : Maybe AllTogether_Favourite
    , my_name : Maybe String
    , abc : AllTogether_NestedAbc
    , answer : AllTogether_Answer
    }


type alias AllTogether_NestedAbc =
    { a : Int
    , b : Int
    , c : Int
    }


type alias Scalar =
    { myDouble : Float
    , myFloat : Float
    , myInt32 : Int
    , myUint32 : Int
    , mySint32 : Int
    , myFixed32 : Int
    , mySfixed32 : Int
    , myBool : Bool
    , myString : String
    , myBytes : Bytes
    }


type AllTogether_Answer
    = Maybe_AllTogether_Answer Int
    | Yes_AllTogether_Answer
    | No_AllTogether_Answer


type AllTogether_Favourite
    = MyStr_AllTogether_Favourite String
    | MyNum_AllTogether_Favourite Int
    | Selection_AllTogether_Favourite Scalar


emptyAllTogether : AllTogether
emptyAllTogether =
    AllTogether [] Dict.empty Nothing Nothing emptyAllTogether_NestedAbc emptyAllTogether_Answer


emptyAllTogether_NestedAbc : AllTogether_NestedAbc
emptyAllTogether_NestedAbc =
    AllTogether_NestedAbc 0 0 0


emptyScalar : Scalar
emptyScalar =
    Scalar 0 0 0 0 0 0 0 False "" (BE.encode (BE.sequence []))


emptyAllTogether_Answer : AllTogether_Answer
emptyAllTogether_Answer =
    Maybe_AllTogether_Answer 0


allTogetherDecoder : PD.Decoder AllTogether
allTogetherDecoder =
    let
        allTogether_FavouriteDecoder =
            [ ( 3, PD.map MyStr_AllTogether_Favourite PD.string )
            , ( 4, PD.map MyNum_AllTogether_Favourite PD.int32 )
            , ( 5, PD.map Selection_AllTogether_Favourite scalarDecoder )
            ]

        example_AllTogether_MyNameDecoder =
            [ ( 6, PD.string )
            ]
    in
    PD.message emptyAllTogether
        [ PD.repeated 1 PD.string .myList (\v m -> { m | myList = v })
        , PD.mapped 2 ( "", False ) PD.string PD.bool .myMap (\v m -> { m | myMap = v })
        , PD.oneOf allTogether_FavouriteDecoder (\v m -> { m | favourite = v })
        , PD.oneOf example_AllTogether_MyNameDecoder (\v m -> { m | my_name = v })
        , PD.optional 7 allTogether_NestedAbcDecoder (\v m -> { m | abc = v })
        , PD.optional 8 allTogether_AnswerDecoder (\v m -> { m | answer = v })
        ]


allTogether_NestedAbcDecoder : PD.Decoder AllTogether_NestedAbc
allTogether_NestedAbcDecoder =
    PD.message emptyAllTogether_NestedAbc
        [ PD.optional 1 PD.int32 (\v m -> { m | a = v })
        , PD.optional 2 PD.int32 (\v m -> { m | b = v })
        , PD.optional 3 PD.int32 (\v m -> { m | c = v })
        ]


scalarDecoder : PD.Decoder Scalar
scalarDecoder =
    PD.message emptyScalar
        [ PD.optional 1 PD.double (\v m -> { m | myDouble = v })
        , PD.optional 2 PD.float (\v m -> { m | myFloat = v })
        , PD.optional 3 PD.int32 (\v m -> { m | myInt32 = v })
        , PD.optional 5 PD.uint32 (\v m -> { m | myUint32 = v })
        , PD.optional 7 PD.sint32 (\v m -> { m | mySint32 = v })
        , PD.optional 9 PD.fixed32 (\v m -> { m | myFixed32 = v })
        , PD.optional 11 PD.sfixed32 (\v m -> { m | mySfixed32 = v })
        , PD.optional 13 PD.bool (\v m -> { m | myBool = v })
        , PD.optional 14 PD.string (\v m -> { m | myString = v })
        , PD.optional 15 PD.bytes (\v m -> { m | myBytes = v })
        ]


allTogether_AnswerDecoder : PD.Decoder AllTogether_Answer
allTogether_AnswerDecoder =
    let
        conv v =
            case v of
                1 ->
                    Yes_AllTogether_Answer

                2 ->
                    No_AllTogether_Answer

                wire ->
                    Maybe_AllTogether_Answer wire
    in
    PD.map conv PD.int32


allTogetherEncoder : AllTogether -> PE.Encoder
allTogetherEncoder v =
    let
        allTogether_FavouriteEncoder o =
            case o of
                Just (MyStr_AllTogether_Favourite data) ->
                    [ ( 3, PE.string data ) ]

                Just (MyNum_AllTogether_Favourite data) ->
                    [ ( 4, PE.int32 data ) ]

                Just (Selection_AllTogether_Favourite data) ->
                    [ ( 5, scalarEncoder data ) ]

                Nothing ->
                    []

        example_AllTogether_MyNameEncoder o =
            case o of
                Just data ->
                    [ ( 6, PE.string data ) ]

                Nothing ->
                    []
    in
    PE.message <|
        [ ( 1, PE.list PE.string v.myList )
        , ( 2, PE.dict PE.string PE.bool v.myMap )
        , ( 7, allTogether_NestedAbcEncoder v.abc )
        , ( 8, allTogether_AnswerEncoder v.answer )
        ]
            ++ allTogether_FavouriteEncoder v.favourite
            ++ example_AllTogether_MyNameEncoder v.my_name


allTogether_NestedAbcEncoder : AllTogether_NestedAbc -> PE.Encoder
allTogether_NestedAbcEncoder v =
    PE.message <|
        [ ( 1, PE.int32 v.a )
        , ( 2, PE.int32 v.b )
        , ( 3, PE.int32 v.c )
        ]


scalarEncoder : Scalar -> PE.Encoder
scalarEncoder v =
    PE.message <|
        [ ( 1, PE.double v.myDouble )
        , ( 2, PE.float v.myFloat )
        , ( 3, PE.int32 v.myInt32 )
        , ( 5, PE.uint32 v.myUint32 )
        , ( 7, PE.sint32 v.mySint32 )
        , ( 9, PE.fixed32 v.myFixed32 )
        , ( 11, PE.sfixed32 v.mySfixed32 )
        , ( 13, PE.bool v.myBool )
        , ( 14, PE.string v.myString )
        , ( 15, PE.bytes v.myBytes )
        ]


allTogether_AnswerEncoder : AllTogether_Answer -> PE.Encoder
allTogether_AnswerEncoder v =
    let
        conv =
            case v of
                Maybe_AllTogether_Answer wire ->
                    wire

                Yes_AllTogether_Answer ->
                    1

                No_AllTogether_Answer ->
                    2
    in
    PE.int32 conv
