-- Generated by protoc-gen-elmgen. DO NOT EDIT!


module ExampleTwirp exposing (..)

import Example as Data
import Http
import Protobuf.Decode as PD
import Protobuf.Encode as PE


ourService_AnotherMethod : (Result Http.Error Data.Scalar -> msg) -> String -> Data.AllTogether -> Cmd msg
ourService_AnotherMethod msg api data =
    Http.post
        { url = api ++ "/example.OurService/AnotherMethod"
        , body =
            Data.allTogetherEncoder data
                |> PE.encode
                |> Http.bytesBody "application/protobuf"
        , expect = PD.expectBytes msg Data.scalarDecoder
        }


ourService_OurRpcMethod : (Result Http.Error Data.AllTogether -> msg) -> String -> Data.Scalar -> Cmd msg
ourService_OurRpcMethod msg api data =
    Http.post
        { url = api ++ "/example.OurService/OurRPCMethod"
        , body =
            Data.scalarEncoder data
                |> PE.encode
                |> Http.bytesBody "application/protobuf"
        , expect = PD.expectBytes msg Data.allTogetherDecoder
        }
